# main text of home
name: 叮咚
bio: set target,daily progress,build system.
bio-url: 

# twitter summary info
description: A blog about reubin.site 叮咚

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/profile/github_profile.png
profile_bk: assets/profile/profile_bk_2017.jpg
author: 叮咚
reubinqr:  
reubingzh: 叮咚同学

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: /2020/02/02/resume.html

url: https:// 
# your url: http://USERNAME.github.io

# permalink: /:title/
permalink: /:year/:month/:day/:title.html

# To enable google analytics, supply your token below
analytics-google: ''

analytics-baidu: ' '


# To enable piwik tracking, supply your url & site ID below
analytics-piwik-url: ' '
analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
enable_disque: false

disqus:
  shortname: reubin-name # enter this from your disqus account
  categories: [blog, note, product] # only show disqus for posts that have these categories  

# if you don't want comments in your posts, leave categories empty
enable_valine: true

valine:
  shortname: reubin-name # enter this from your disqus account
  categories: [blog, note, product,tech,daily] # only show disqus for posts that have these categories  
  appId: ' '
  appKey: ' '
  visitors: true

# if you don't have any of social below, comment the line
# 文件在include 下面的 icon  
weibo: reubin
# jianshu:  
zhihu: reubin
juejin:  
# facebook: 
# twitter:  
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube:  
# spotify: myspotify
github: reubin
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow:  
# quora: userquora
# reddit: username
# medium:  
# vimeo: myvimeo
# lanyrd: mylanyrd
# email: reubin#gmail.com
rss: true

authors:
    gudong:
        name: 叮咚
        bio: 人惟求旧，物惟求新。
        about: /about
        external-image: false
        picture: assets/profile/github_profile.png
        twitter:  

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 720px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

#note
note: false

tech: true
daily: true

# personal product
product: true

# if you don't need "about" or "blog", comment them out below
about: true

blog: true

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url:  

markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge 
